version: 2.1
orbs: 
  bridgecrew: bridgecrew/bridgecrew@1.0.5

jobs:
  build:
    executor: bridgecrew/default
    steps:
      - checkout
      - bridgecrew/scan:
          api-key-variable: BC_API_KEY
          directory: ./terraform
          output: json
          soft-fail: true
workflows: null

