version: 2.1
orbs: 
  bridgecrew: bridgecrew/bridgecrew@1.0.5

jobs:
  build:
    machine: true
    steps:
      - checkout
      - bridgecrew/install
      - bridgecrew/scan:
          api-key-variable: BC_API_KEY
          directory: .
workflows: null
